export const PH = {
  INSTRUCTOR_NAME:   'Placeholder 1: Instructor Name',
  INSTRUCTOR_EMAIL:  'Placeholder 2: Instructor Email',
  INSTRUCTOR_PHONE:  'Placeholder 3: Instructor Phone',
  INSTRUCTOR_OFFICE: 'Placeholder 4: Instructor Office',
  INSTRUCTOR_HOURS:  'Placeholder 5: Instructor Office Hours',
  TA_NAME:           'Placeholder 6: TA Name',
  TA_EMAIL:          'Placeholder 7: TA Email',
  TA_PHONE:          'Placeholder 8: TA Phone',
  TA_OFFICE:         'Placeholder 9: TA Office',
  TA_HOURS:          'Placeholder 10: TA Office Hours',
  SELECT_COURSE:     'Placeholder 11: Select Course',
  SELECT_EXAM:       'Placeholder 12: Select Exam',
  SELECT_STUDENT:    'Placeholder 13: Select Student',
  NO_ALERTS:         'Placeholder 14: No Alerts Available',
  NO_HEATMAP:        'Placeholder 15: No Heatmap Data',
  NO_STUDY_PLAN:     'Placeholder 16: No Study Plan Available',
  NO_CONCEPTS:       'Placeholder 17: No Concepts Available',
  NO_STUDENTS:       'Placeholder 18: No Students Available',
  NO_INTERVENTIONS:  'Placeholder 19: No Interventions Available',
  NO_DATA:           'Placeholder 20: No Data Available',
  LOADING:           'Loading...',
  ERROR_GENERIC:     'Something went wrong. Please try again.',
} as const;
